theme: jekyll-theme-minimal
title: Emma Brown Portfolio <anything you like>
description: Listed here are links to my work from my time as an undergraduate applied mathematics major at Wheaton College.

